In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
from pathlib import Path
import polars as pl
from influxdb_client  import InfluxDBClient , WriteOptions
import yaml
import requests


current_file = Path(globals().get('__vsc_ipynb_file__', None))
parent_dir = current_file.parent.parent
os.chdir(parent_dir)
print("Changed working directory to:", Path.cwd())

Changed working directory to: /home/legacy/Projects/Weather_forecasting_with_MLOps

In [3]:
from dotenv import load_dotenv
load_dotenv("mlops_services/.env.mlops")

True

In [4]:
os.getenv('INFLUXDB_URL')

'http://localhost:8086'

In [5]:
from mlops_services.src.utils.load_config import Config
weather_config = Config.from_yaml(Path('mlops_services/config/weather_data.yaml'))

In [6]:
weather_config.all_cities

['BLR', 'DEL']

In [ ]:
from mlops_services.src.components.weather_access import HistoricWeather
hist_weather = HistoricWeather(weather_config,'BLR')

In [8]:
hist_df = hist_weather.get_df( start='2023-01-01',end='2025-06-30')
hist_df.head()

shape: (5, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ time      ┆ temperatu ┆ relative_ ┆ dew_point ┆ … ┆ utc_offse ┆ timezone  ┆ timezone_ ┆ elevatio │
│ ---       ┆ re_2m     ┆ humidity_ ┆ _2m       ┆   ┆ t_seconds ┆ ---       ┆ abbreviat ┆ n        │
│ datetime[ ┆ ---       ┆ 2m        ┆ ---       ┆   ┆ ---       ┆ str       ┆ ion       ┆ ---      │
│ μs, UTC]  ┆ f64       ┆ ---       ┆ f64       ┆   ┆ i32       ┆           ┆ ---       ┆ f64      │
│           ┆           ┆ i64       ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2022-12-3 ┆ 16.2      ┆ 74        ┆ 11.7      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 18:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2022-12-3 ┆ 16.1      ┆ 75        ┆ 11.6      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 19:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2022-12-3 ┆ 15.6      ┆ 80        ┆ 12.1      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 20:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2022-12-3 ┆ 15.3      ┆ 84        ┆ 12.7      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 21:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2022-12-3 ┆ 14.8      ┆ 89        ┆ 13.1      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 22:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [90]:
with open('units.yaml', 'w', encoding='utf-8') as f:
    yaml.dump(hist_df['hourly_units'][0], f, allow_unicode=True)

In [74]:
res.keys()

dict_keys(['latitude', 'longitude', 'generationtime_ms', 'utc_offset_seconds', 'timezone', 'timezone_abbreviation', 'elevation', 'hourly_units', 'hourly'])

In [11]:
hist_df.tail()

shape: (5, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ time      ┆ temperatu ┆ relative_ ┆ dew_point ┆ … ┆ utc_offse ┆ timezone  ┆ timezone_ ┆ elevatio │
│ ---       ┆ re_2m     ┆ humidity_ ┆ _2m       ┆   ┆ t_seconds ┆ ---       ┆ abbreviat ┆ n        │
│ datetime[ ┆ ---       ┆ 2m        ┆ ---       ┆   ┆ ---       ┆ str       ┆ ion       ┆ ---      │
│ μs, UTC]  ┆ f64       ┆ ---       ┆ f64       ┆   ┆ i32       ┆           ┆ ---       ┆ f64      │
│           ┆           ┆ i64       ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2025-06-3 ┆ 23.9      ┆ 72        ┆ 18.5      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 13:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-06-3 ┆ 23.4      ┆ 75        ┆ 18.8      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 14:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-06-3 ┆ 22.6      ┆ 78        ┆ 18.7      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 15:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-06-3 ┆ 21.9      ┆ 82        ┆ 18.7      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 16:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2025-06-3 ┆ 21.3      ┆ 85        ┆ 18.7      ┆ … ┆ 19800     ┆ Asia/Kolk ┆ GMT+5:30  ┆ 918.0    │
│ 0         ┆           ┆           ┆           ┆   ┆           ┆ ata       ┆           ┆          │
│ 17:30:00  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ UTC       ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [13]:
from mlops_services.src.utils.db_io import InfluxDB
db = InfluxDB(bucket='WEATHER_DATA_RAW',measurement="city_BLR1")
db.ping()

InfluxDB connection successful.

True

In [10]:
db.delete_city()

In [12]:
db.push_to_db(hist_df)

In [9]:
from mlops_services.src.utils.time_utils import convert_to_utc

In [26]:
convert_to_utc('2023-01-01 00:00','2025-06-30 23:00', tz="Asia/Kolkata", from_format="%Y-%m-%d %H:%M",
                                                        to_format="%Y-%m-%dT%H:%M")

('2023-01-01 00:00', '2025-06-30 23:00')

('2022-12-31T18:30', '2025-06-30T17:30')

In [14]:
start , end = convert_to_utc('2023-01-01 00:00','2025-07-01 00:00', tz="Asia/Kolkata",from_format="%Y-%m-%d %H:%M",
                                                        to_format="%Y-%m-%dT%H:%M:%SZ")
hist_df1 = db.fetch_as_df(start=start,end=end)
hist_df1

('2023-01-01 00:00', '2025-07-01 00:00')

shape: (0, 0)
┌┐
╞╡
└┘

In [12]:
db.measurement

'city_BLR'

In [16]:
hist_df1.write_csv('mlops_services/data/historic/historic_BLR.csv')
hist_df1.write_parquet('mlops_services/data/historic/historic_BLR.parquet')

In [17]:
hist_df2 = pl.read_parquet('mlops_services/data/historic/historic_BLR.parquet')
hist_df2

shape: (21_888, 28)
┌─────────┬───────┬────────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ result  ┆ table ┆ _start     ┆ _stop      ┆ … ┆ weather_co ┆ wind_direc ┆ wind_gusts ┆ wind_spee │
│ ---     ┆ ---   ┆ ---        ┆ ---        ┆   ┆ de         ┆ tion_10m   ┆ _10m       ┆ d_10m     │
│ str     ┆ i64   ┆ datetime[n ┆ datetime[n ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│         ┆       ┆ s, UTC]    ┆ s, UTC]    ┆   ┆ i64        ┆ i64        ┆ f64        ┆ f64       │
╞═════════╪═══════╪════════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 0          ┆ 97         ┆ 15.1       ┆ 9.4       │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 0          ┆ 96         ┆ 16.2       ┆ 9.8       │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 3          ┆ 96         ┆ 16.2       ┆ 9.8       │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 2          ┆ 100        ┆ 16.9       ┆ 10.2      │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 2          ┆ 99         ┆ 16.9       ┆ 9.1       │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ …       ┆ …     ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 51         ┆ 268        ┆ 34.2       ┆ 11.7      │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 51         ┆ 254        ┆ 31.3       ┆ 14.8      │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 3          ┆ 260        ┆ 36.4       ┆ 15.9      │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 3          ┆ 263        ┆ 35.6       ┆ 14.9      │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
│ _result ┆ 0     ┆ 2022-12-31 ┆ 2025-06-30 ┆ … ┆ 3          ┆ 262        ┆ 33.1       ┆ 13.1      │
│         ┆       ┆ 18:30:00   ┆ 18:30:00   ┆   ┆            ┆            ┆            ┆           │
│         ┆       ┆ UTC        ┆ UTC        ┆   ┆            ┆            ┆            ┆           │
└─────────┴───────┴────────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [47]:
js=hist_weather.pull_data()

In [43]:
base_url = "https://archive-api.open-meteo.com/v1/archive"


response = requests.get(base_url, params=hist_weather.params)
response.json()

{'reason': "Invalid date format. Make sure to use 'YYYY-MM-DD'", 'error': True}